MACOSX_DEPLOYMENT_TARGET:   # [osx]
- '10.12'                   # [osx]
CONDA_BUILD_SYSROOT:        # [osx]
- /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk  # [osx]
