{% set version = "5.6.2" %}

package:
  name: qt
  version: {{ version }}

source:
  url: http://download.qt.io/official_releases/qt/5.6/{{ version }}/single/qt-everywhere-opensource-src-{{ version }}.tar.gz
  sha256: 7551f5af1312082c3c8ab52f5e102e3f83aae2dd96dc4a3a9a197f3e58b3214c
  patches:
    - 0005-Remove-unused-include-sys-signalfd.h.patch
    - 0006-zlib_dependency-Add-EXTRA_INCLUDEPATH-for-system-zli.patch
    - 0007-CentOS5-Do-not-use-strict_c-when-using-c-11.patch
    - 0008-disable-Ubuntu-overlay-scrollbars-as-they-don-t-play.patch
    # qtbase
    - 0004-VS2008-Add-typedefs-for-more-int-_t-and-define-_STDI.patch  # [win]
    - 0009-osx-force-10.9-deployment-target.patch  # [osx]
    - 0010-osx-xctest-check.patch  # [osx]
    # qt3d
    - 0001-Don-t-re-typedef-int-_t-if-_STDINT-is-defined.patch  # [win]
    # qtwinextras
    - 0001-shobjidl-Fix-compile-guard-around-SHARDAPPIDINFOLINK.patch  # [win]

build:
  number: 8
  skip: True  # [osx or win]
  detect_binary_files_with_prefix: true
  features:
    - vc9  # [win and py27]
    - vc14  # [win and (py35 or py36)]

requirements:
  build:
    - python  # [win]
    - python 2.7*  # [unix]
    - 7za  # [win]
    - bison  # [linux]
    - flex  # [linux]
    - gperf  # [linux]
    - curl >=7.44.0,<8  # [win]
    - msinttypes  # [win and py27]
    - perl
    - freetype 2.8.1  # [linux]
    - fontconfig 2.12.*  # [linux]
    - openssl 1.0.*  # [not osx]
    - jpeg 9*
    - zlib 1.2.11
    - libpng >=1.6.32,<1.6.35
    - gst-plugins-base  # [linux]
    - icu 58.*
    - sqlite 3.20.*
    - libxcb  # [linux]
    - dbus  # [linux]
    - vc 9  # [win and py27]
    - vc 14  # [win and (py35 or py36)]
  run:
    - freetype 2.8.1  # [linux]
    - fontconfig 2.12.*  # [linux]
    - openssl 1.0.*  # [not osx]
    - jpeg 9*
    - zlib 1.2.11
    - libpng >=1.6.32,<1.6.35
    - gst-plugins-base  # [linux]
    - icu 58.*
    - sqlite 3.20.*
    - libxcb  # [linux]
    - dbus  # [linux]
    - vc 9  # [win and py27]
    - vc 14  # [win and (py35 or py36)]

test:
  files:
    - test/hello.pro
    - test/main.cpp
  commands:
    - if not exist %LIBRARY_BIN%\\Qt5WebKit.dll exit 1  # [win]
    - test -f $PREFIX/lib/libQt5WebKit.so  # [linux]
    # sql plugin
    - test -f $PREFIX/plugins/sqldrivers/libqsqlite${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_PREFIX%\plugins\sqldrivers\qsqlite.dll exit 1  # [win]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://qt-project.org
  license: LGPL-3.0
  summary: 'Qt is a cross-platform application and UI framework.'
  description: |
    Qt helps you create connected devices, UIs & applications that run
    anywhere on any device, on any operating system at any time.
  doc_url: http://doc.qt.io/
  dev_url: https://github.com/qtproject

extra:
  recipe-maintainers:
    - ccordoba12
    - mingwandroid
    - gillins
    - msarahan
    - ocefpaf
    - stuarteberg
