azure:
  settings_win:
    variables:
      CONDA_BLD_PATH: C:\bld\
build_platform:
  osx_arm64: osx_64
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: default
test_on_native_only: true
