conda_forge_output_validation: true
azure:
  settings_win:
    variables:
      CONDA_BLD_PATH: "C:\\bld\\"
provider: {linux_aarch64: default}
build_platform: {linux_ppc64le: linux_64}
test_on_native_only: true
