jobs:
- job: linux_64
  pool:
    vmImage: ubuntu-16.04
  strategy:
    maxParallel: 8
    matrix:
      linux_c_compilergcccxx_compilergxx:
        CONFIG: linux_c_compilergcccxx_compilergxx
  steps:
  - script: |
      sudo pip install --upgrade pip
      sudo pip install setuptools shyaml
    displayName: Install dependencies

  - script: .azure-pipelines/run_docker_build.sh
    displayName: Run docker build